### PR TITLE
Adding seed option

### PR DESCRIPTION
**Pull request by msoos**
Hi,

This pull request adds an option to give seed. By default the system works as before. However, if the "-seed N" option is set to be something other than -1, then it sets that value as seed. This allows for reproducibility, if needed.

### CODE REVIEW

**Comment by ZaydH** [comment]
Hi Mate, I really appreciate you submitting this pull request.  I am swamped with an ICML deadline at the moment.  It should pass by February 7.  Do you mind if I look at this after that?  If you have a pressing need, I will prioritize it for you.

**Comment by msoos** [comment]
Thanks! No worries, all good, please check after the deadline! Good luck in
the meanwhile with your paper :)

We are using your tool in our upcoming paper so it'd be nice if we could
link to your git repo rather than ours in the final paper. We have time for
the final version so no rush right now :) Thanks again for your tool, it's
good stuff,

Mate

**Comment by ZaydH** [comment]
Thanks for being understanding.  Once my paper deadline passes, I can work with you to make sure you get whatever you need for your submission.

**Review by ZaydH — APPROVED** [review]

**Comment by ZaydH** [comment]
Hi Mate (@msoos)
Thanks for being patient on this.  I accepted the request and released a new version in case that is usual to you all.  Best of luck on the paper!

**Comment by msoos** [comment]
Thanks! Sounds great!

Mate

**Pull request merged**
